### ISSUE TITLE
Issue in creating Leads using "Create" button

### ISSUE THREAD

**Issue by mathew1972** [frappe/crm#397] opened 2024-10-03 11:49 UTC
I can't create Leads using the "Create" button. I keep getting an error message saying, "First Name is mandatory." Please help me fix this issue.
![Leads Issue](https://github.com/user-attachments/assets/0ce5dd2e-00e9-4a18-a7cc-842914495b31)
@shariquerik

**Comment by 1ubuntuuser** [comment] 2024-10-09 23:03
Hello, this is a duplicate of #387 This is a partial work around there, but not a full solution yet.

**Comment by shariquerik** [comment] 2024-10-12 09:35
@1ubuntuuser Not sure why default values are not created on install. But I have added a "Restore Defaults" button to restore it from FCRM Settings doctype.

**Closed** 2024-12-30 17:39 UTC
